// <auto-generated />
namespace KhoiDepTraiShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_key : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_key));
        
        string IMigrationMetadata.Id
        {
            get { return "201801160944215_add_key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
